<?php

namespace Jetimob\Asaas\Entity\Account;

enum DocumentTypeEnum: string
{
    case IDENTIFICATION = 'IDENTIFICATION';
    case SOCIAL_CONTRACT = 'SOCIAL_CONTRACT';
    case ENTREPRENEUR_REQUIREMENT = 'ENTREPRENEUR_REQUIREMENT';
    case CUSTOM = 'CUSTOM';
    case MINUTES_OF_ELECTION = 'MINUTES_OF_ELECTION';
    case POWER_OF_ATTORNEY = 'POWER_OF_ATTORNEY';
    case IDENTIFICATION_SELFIE = 'IDENTIFICATION_SELFIE';
    case ALLOW_BANK_ACCOUNT_DEPOSIT_STATEMENT = 'ALLOW_BANK_ACCOUNT_DEPOSIT_STATEMENT';
    case EMANCIPATION_OF_MINORS = 'EMANCIPATION_OF_MINORS';
    case INVOICE = 'INVOICE';
    case MEI_CERTIFICATE = 'MEI_CERTIFICATE';
    case MINUTES_OF_CONSTITUTION = 'MINUTES_OF_CONSTITUTION';
}
